### ISSUE TITLE
Logging in...Attempt 1 at connecting failed: TimeoutError:

### ISSUE THREAD

**Issue by MsFGz** [bellingcat/telegram-phone-number-checker#30] opened 2024-05-15 09:47 UTC
Logging in...Attempt 1 at connecting failed: TimeoutError:
Attempt 2 at connecting failed: TimeoutError:
Attempt 3 at connecting failed: TimeoutError:
Attempt 4 at connecting failed: TimeoutError:
Attempt 5 at connecting failed: TimeoutError:
Attempt 6 at connecting failed: TimeoutError:

**Comment by GalenReich** [comment] 2024-05-16 16:07
Closing as duplicate of #29

**Closed by GalenReich** 2024-05-16 16:07 UTC
Labels: duplicate
